# Generated by Django 4.1.3 on 2023-08-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addarticle',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('archived', 'Archived'), ('published', 'Published')], default=None, max_length=20, null=True),
        ),
    ]
