# Generated by Django 4.1.3 on 2025-02-23 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=800)),
                ('abstract', models.TextField(default=None)),
                ('key_word_1', models.CharField(default=None, max_length=100)),
                ('key_word_2', models.CharField(default=None, max_length=100)),
                ('key_word_3', models.CharField(default=None, max_length=100)),
                ('body', models.TextField(default=None)),
                ('created_date_jalali', django_jalali.db.models.jDateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('archived', 'Archived'), ('draft', 'Draft')], default=None, max_length=20, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Addarticle',
        ),
    ]
