# Generated by Django 5.1.6 on 2025-03-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('archived', 'Archived'), ('draft', 'Draft')], default=None, max_length=20, null=True),
        ),
    ]
