# Generated by Django 5.1.6 on 2025-03-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_article_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('archived', 'Archived'), ('draft', 'Draft')], default=None, max_length=20, null=True),
        ),
    ]
