# Generated by Django 5.1.6 on 2025-04-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_article_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('archived', 'Archived')], default=None, max_length=20, null=True),
        ),
    ]
